# Generated by Django 5.2.8 on 2025-11-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.TextField(help_text='Descreva os sintomas do paciente', verbose_name='Histórico / Queixas')),
                ('prescricao', models.TextField(help_text='Medicamentos e orientações', verbose_name='Prescrição / Receita')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='core.agendamento')),
            ],
        ),
    ]
