# Generated by Django 5.2.8 on 2025-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil'),
        ),
    ]
