# Generated by Django 5.2.8 on 2025-11-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Medicamento')),
                ('generico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Genérico')),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('AGUARDANDO', 'Na Sala de Espera'), ('CANCELADO', 'Cancelado'), ('REALIZADO', 'Realizado')], default='AGENDADO', max_length=10),
        ),
    ]
