# Generated by Django 5.2.8 on 2025-11-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicamento_alter_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Está Pago?'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Valor da Consulta'),
        ),
    ]
