# Generated by Django 5.2.8 on 2025-11-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendamento_pago_agendamento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Avaliação (1-5)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='comentario_paciente',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário'),
        ),
    ]
