# Generated by Django 5.2.8 on 2025-11-23 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paciente_sexo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_horario']},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='atualizado_em',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='avaliacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estrelas'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Queixa Inicial'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('AGUARDANDO', 'Na Sala de Espera'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='generico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genérico'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='historico',
            field=models.TextField(verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='prescricao',
            field=models.TextField(verbose_name='Prescrição'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
