# Generated by Django 5.2.8 on 2025-11-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_agendamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='nivel_dor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nível de Dor'),
        ),
    ]
